framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection: true

    http_method_override: false

    session:
        handler_id: session.handler.native_file
        cookie_secure: auto
        cookie_samesite: strict
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

    dama_doctrine_test:
        enable_static_connection: true
        enable_static_meta_data_cache: true
        enable_static_query_cache: true

